services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "3003:3003"
    env_file:
      - .env.docker
    networks:
      - backend

networks:
  backend:
    external: true